In [8]:
import numpy as np

num_inputs = 2
input_shape = (4, 5, 6)
output_dim = 3

input_size = num_inputs * np.prod(input_shape)
weight_size = output_dim * np.prod(input_shape)

x = np.linspace(-0.1, 0.5, num=input_size).reshape(num_inputs, *input_shape)

In [12]:
x.shape
y = x[1,:,:,:].flatten()
y.shape

(120,)

In [26]:
t = x.reshape(x.shape[0], -1)
t.shape

(2, 120)

In [30]:
a = np.array([[1,2,3,4],[32,4,23,5],[2,4,5,6]])
a.shape

(3, 4)

In [31]:
b = np.array([1,2,3,1])
a+b

array([[ 2,  4,  6,  5],
       [33,  6, 26,  6],
       [ 3,  6,  8,  7]])

In [32]:
b

array([1, 2, 3, 1])

In [34]:
np.max(0,b)

TypeError: only integer scalar arrays can be converted to a scalar index

In [35]:
def maxx(x):
    t = max(0,x)
    return t

maxx(b)
    

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [37]:
np.maximum(0,b)

array([1, 2, 3, 1])

In [38]:
b = np.array([-1,2,3,1])
np.maximum(0,b)

array([0, 2, 3, 1])

In [39]:
[b<=0]

[array([ True, False, False, False], dtype=bool)]

In [40]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [41]:
np.sum(b)

5

In [43]:
q = np.array([[1,2,3], [2,3,4]])
np.sum(q)**2

225

In [1]:
[{'mode': 'train'} for i in range(5 - 1)]

[{'mode': 'train'}, {'mode': 'train'}, {'mode': 'train'}, {'mode': 'train'}]

In [4]:
"arrasdy"+str(1)

'arrasdy1'

In [2]:
import numpy as np
a = np.array([[1,2,3],[4,5,6,]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
mu = np.mean(a, axis =0 )
mu

array([ 2.5,  3.5,  4.5])

In [9]:
var = np.var(a, axis = 0)
var

array([ 2.25,  2.25,  2.25])

In [12]:
a+mu

array([[  3.5,   5.5,   7.5],
       [  6.5,   8.5,  10.5]])

In [13]:
(a+mu)/var

array([[ 1.55555556,  2.44444444,  3.33333333],
       [ 2.88888889,  3.77777778,  4.66666667]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
b = (np.random.rand(*a.shape) < 0.6)/0.5
b

array([[ 2.,  2.,  0.],
       [ 0.,  0.,  2.]])

In [15]:
a *= b
a

array([[1, 2, 3],
       [4, 0, 0]])

In [19]:
d = np. array([1,2,3])
len(d)
for i in range(len(d)):
    print (i)

0
1
2


In [21]:
for i in range(5,0,-1):
    print (i)

5
4
3
2
1


In [1]:
import numpy as np
a = np.array([[1,2,3],[4,5,6,]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
np.random.random_sample(a.shape) > 0.9

array([[False, False, False],
       [False, False, False]], dtype=bool)