In [15]:
import numpy as np
from past.builtins import xrange

A = np.array([[1,2],[3,4],[3,4]])
B = np.array([[2,4],[6,8]])
for i in xrange(A.shape[0]):
    for j in xrange(B.shape[0]):
        t= np.linalg.norm((np.subtract(A[i,:], B[j,:])))
        print (i,j, t)
        
    

0 0 2.2360679775
0 1 7.81024967591
1 0 1.0
1 1 5.0
2 0 1.0
2 1 5.0


In [13]:
print (xrange(B.shape[0]))

range(0, 2)


In [45]:
print(np.zeros((2)))

[ 0.  0.]


In [53]:
a = np.array([1,2,3,42,545,2,3])
b = np.array([[1,2,3,4,5,6,7,8,9]])
v = (np.argsort(a)[0:3])
print (v)
print (b[:,v])
print (statistics.mode(a))

[0 1 5]
[[1 2 6]]


StatisticsError: no unique mode; found 2 equally common values

In [48]:
print (len(set(a)))

TypeError: unhashable type: 'numpy.ndarray'

In [55]:
import collections
print (collections.Counter(a))

Counter({2: 2, 3: 2, 1: 1, 42: 1, 545: 1})


In [56]:
np.bincount(a)

array([0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0,

In [65]:
for i in range(np.shape(np.bincount(a))[0]):
    if((np.bincount(a))[i]==max(np.bincount(a))):
        print (i)
        

2
3


In [66]:
k = []


In [67]:
k.append(2)

In [68]:
print (k)

[2]


In [82]:
a = np.array([[2,3],[5,4],[3,2],[9,7]])
b = np.array([[1,0], [0,1]])
print (np.subtract(b,a))
print ((a-b)*(a-b))
v = np.sum(((a-b)*(a-b)), axis =1)
print (np.sqrt(v))

ValueError: operands could not be broadcast together with shapes (2,2) (2,4) 

In [83]:
print (a, a.T)

[[2 3]
 [5 4]
 [3 2]
 [9 7]] [[2 5 3 9]
 [3 4 2 7]]


In [96]:
print (a)
print (np.sum(a, axis=1))
print (np.sum(a**2))

[[2 3]
 [5 4]
 [3 2]
 [9 7]]
[ 5  9  5 16]
197


In [98]:
a = 5
for i in range(a):
    print (i)

0
1
2
3
4


In [101]:
a = np.array([[2,3],[5,4],[3,2],[9,7], [3,4]])
print (len(a))

5


In [111]:
b = np.array([[1,2],[44,3]])
c = np.vstack([a,b])
print (c, len(c))

[[ 2  3]
 [ 5  4]
 [ 3  2]
 [ 9  7]
 [ 3  4]
 [ 1  2]
 [44  3]] 7


In [116]:
b = []
b.append(4)

print (b)

[4]


In [129]:
d = []
d.append(a)
print (d[0])
d.append(c)
print (d)
print (d[0].dtype)

[[2 3]
 [5 4]
 [3 2]
 [9 7]
 [3 4]]
[array([[2, 3],
       [5, 4],
       [3, 2],
       [9, 7],
       [3, 4]]), array([[ 2,  3],
       [ 5,  4],
       [ 3,  2],
       [ 9,  7],
       [ 3,  4],
       [ 1,  2],
       [44,  3]])]
int64


In [128]:
print (a)
print (a[2:4,:])

[[2 3]
 [5 4]
 [3 2]
 [9 7]
 [3 4]]
[[3 2]
 [9 7]]


In [3]:
import numpy as np
a = np.array([[1,2,3],[2,3,4],[5,4,2]])
np.sum(a, axis=0)[0]

8

In [6]:
np.exp(a)

array([[   2.71828183,    7.3890561 ,   20.08553692],
       [   7.3890561 ,   20.08553692,   54.59815003],
       [ 148.4131591 ,   54.59815003,    7.3890561 ]])

In [35]:
b = np.sum(np.exp(a), axis = 1)
print (b)

[  30.19287485   82.07274306  210.40036523]


In [38]:
t =(a[np.arange(len(a)), [1,2,1]])
print (t)

[2 4 4]


In [39]:
b/t


array([ 15.09643743,  20.51818576,  52.60009131])

In [41]:
np.log(a)

array([[ 0.        ,  0.69314718,  1.09861229],
       [ 0.69314718,  1.09861229,  1.38629436],
       [ 1.60943791,  1.38629436,  0.69314718]])

In [42]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [5, 4, 2]])

In [43]:
sum(a)

array([8, 9, 9])

In [44]:
np.sum(a)

26

In [45]:
a 

array([[1, 2, 3],
       [2, 3, 4],
       [5, 4, 2]])

In [59]:
b = [1,2,3]
r = (a.T/b).T

In [57]:
[1, 6]

[1, 6]

In [58]:
a = np.array([1,4,7])
for i in a:
    print (i)

1
4
7


In [60]:
r

array([ 1.        ,  2.        ,  2.33333333])

In [63]:
a = np.array([[1,2,3],[2,3,4],[5,4,2]])
np.max(a, axis = 1)

array([3, 4, 5])

In [67]:
c = np.argmax(a, axis = 1)

In [68]:
d = np.array([2,1,0])
d==c

array([ True, False,  True], dtype=bool)

In [69]:
sum(d==c)

2

In [70]:
w = {}
w[(1,2)] = 3

In [71]:
w

{(1, 2): 3}

In [72]:
abs(-3)

3

In [73]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [5, 4, 2]])

In [75]:
np.sum(a)

26

In [79]:
b = np.array([1,2,3])
(a.T- b).T +

array([[ 0,  1,  2],
       [ 0,  1,  2],
       [ 2,  1, -1]])

In [80]:
(a.T- b).T + 1

array([[1, 2, 3],
       [1, 2, 3],
       [3, 2, 0]])

In [84]:
def maxx(x):
    t = max(0,x)
    return t
f = np.vectorize(maxx)
a = np.array([[0,2,-3],[-2,3,4],[5,4,2]])
c = f(a)
print (a, c)

[[ 0  2 -3]
 [-2  3  4]
 [ 5  4  2]] [[0 2 0]
 [0 3 4]
 [5 4 2]]


In [6]:
import numpy as np
a = np.array([[1,2,3]])
a.shape

(1, 3)

In [8]:
np.random.choice(9,3)

array([1, 7, 6])

In [9]:
np.empty_like(a)

array([[0, 0, 0]])

In [10]:
a

array([[1, 2, 3]])

In [24]:
a = np.array([[1,2,-3],[-2,3,4],[5,4,2]])
b = np.array([1,4,5])
print (a.shape, b.shape)
a+b

(3, 3) (3,)


array([[ 2,  6,  2],
       [-1,  7,  9],
       [ 6,  8,  7]])

In [25]:
def f(x):
    return max(0,x)
f = np.vectorize(f)
f(a)
    

array([[1, 2, 0],
       [0, 3, 4],
       [5, 4, 2]])

In [27]:
np.exp(a)

array([[  2.71828183e+00,   7.38905610e+00,   4.97870684e-02],
       [  1.35335283e-01,   2.00855369e+01,   5.45981500e+01],
       [  1.48413159e+02,   5.45981500e+01,   7.38905610e+00]])

In [30]:
a


array([[ 1,  2, -3],
       [-2,  3,  4],
       [ 5,  4,  2]])

In [35]:
c = np.sum(a, axis = 1)
c

array([ 0,  5, 11])

In [34]:
v = np.array([1,2,3])
v

array([1, 2, 3])

In [39]:

sum(np.log(v))

1.791759469228055

In [40]:
np.exp(-0.81233741)

0.44381946482188661

In [42]:
 0.30482022/1.7704567 

0.17217038970792112

In [43]:
-np.log(0.3644621)

1.0093327109916428

In [46]:
np.sum(a)

16

In [49]:
np.random.randn(a.shape[0], a.shape[1])

array([[ 0.51877561, -0.8198321 ,  2.02717433],
       [ 1.19491856, -0.06404333,  1.43075052],
       [-0.17029246, -0.87510131,  1.80401651]])

In [1]:
q = np.array([[1,2,3],[2,3,4], [4,5,6],[8,7,6], [3,0,8]])
bi = np.array([1,2,3])
print (q, bi)

NameError: name 'np' is not defined

In [53]:
q+bi

array([[ 2,  4,  6],
       [ 3,  5,  7],
       [ 5,  7,  9],
       [ 9,  9,  9],
       [ 4,  2, 11]])

In [68]:
v = np.tile((bi[:, np.newaxis].T), (5,1))
q+v

array([[ 2,  4,  6],
       [ 3,  5,  7],
       [ 5,  7,  9],
       [ 9,  9,  9],
       [ 4,  2, 11]])

In [63]:
np.shape(bi[:, np.newaxis].T)

(1, 3)

In [70]:
p = np.identity(3)

In [71]:
p[1].shape

(3,)

In [73]:
np.sum(q, axis = 0)

array([18, 17, 27])

In [74]:
np.unique(bi)

array([1, 2, 3])

In [75]:
np.empty_like(q)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [82]:
for i, x in enumerate(q):
    print (i)

0
1
2
3
4


In [86]:
np.shape(np.ones([4,4]))

(4, 4)

In [87]:
dL_dW1 = np.empty_like(W1)
    dL_db1 = np.empty_like(b1)[:, np.newaxis]
    dL_dW2 = np.empty_like(W2)
    dL_db2 = np.empty_like(b2)[:, np.newaxis]
    
    # Backward pass: compute gradients
    grads = {}
    #print (W2.shape[0])
    for i, x in enumerate(X):
        dL_dS = prob[i].T[:, np.newaxis]
        dL_dS[y[i]] -= 1
        dS_dZ = W2
        dS_dW2 = Z[i]
        dS_db2 = np.ones([scores.shape[1], scores.shape[1]])
        dL_dZ = np.dot(dS_dZ, dL_dS)
        print (dL_dZ.shape)
            
        dL_dW2 += np.dot(dS_dW2.T[:, np.newaxis], dL_dS.T)
        
        dL_db2 += np.dot(dS_db2, dL_dS)
        dZ_dY = np.identity(W2.shape[0])
        dL_dY = np.dot(dZ_dY, dL_dZ)
        dY_dX = W1.T
        dY_dW1 = X[i][:, np.newaxis].T
        dY_db1 = np.identity(W2.shape[0])
        dL_dW1 += np.dot(dL_dY, dY_dW1).T
        dL_db1 += np.dot(dY_db1, dL_dY)
      #  print (dL_dY.shape, dY_db1.shape)
       
    dL_dW1 /= len(X)
    dL_dW2 /= len(X)
    dL_db1 /= len(X)
    dL_db2 /= len(X)
    dL_dW1 += reg*W1
    dL_dW2 += reg*W2

IndentationError: unexpected indent (<ipython-input-87-186ad6c6c317>, line 2)

In [88]:
exp_scores = np.exp(scores)
    correct_cls_score = exp_scores[np.arange(len(X)), y]
    sum_scores = np.sum(exp_scores, axis = 1)
    prob = exp_scores/sum_scores[:, np.newaxis]
    
    loss = correct_cls_score/sum_scores
    loss = np.mean(-np.log(loss))
    loss += (reg*np.sum(W1*W1)) + (reg*np.sum(W2*W2))

IndentationError: unexpected indent (<ipython-input-88-36f194e92d9d>, line 2)

In [26]:
import numpy as np
w = np.array([1,5, 7, 4])
x = np.array([[5,-3], [-8,-9]])
t = w>0


In [25]:
np.where([w>0])

(array([0]), array([0]))

In [32]:
v = np.array([1,2,3])
v.shape
v

array([1, 2, 3])

In [33]:
v = v[:, np.newaxis]
v.shape
v

array([[1],
       [2],
       [3]])

In [36]:
v = v.reshape(3,)
v.shape
v.T

array([1, 2, 3])

In [41]:
np.maximum(0,x)

array([[5, 0],
       [0, 0]])

In [42]:
x

array([[ 5, -3],
       [-8, -9]])

In [44]:

v = np.array([1,2])
v

array([1, 2])

In [48]:
(x.T+v).T

array([[ 6, -2],
       [-6, -7]])

In [51]:
a = np.array([[1,2],[3,4],[4,7],[9,8]])
b = np.array([10, 100])
a+b

array([[ 11, 102],
       [ 13, 104],
       [ 14, 107],
       [ 19, 108]])

In [59]:
a

array([[1, 2],
       [3, 4],
       [4, 7],
       [9, 8]])

In [58]:
t = np.argmax(a, axis = 0)
t

array([3, 3])

In [1]:
list(range(10, 2+3))

[]

In [2]:
t = list(range(10, 2 + 3))

In [3]:
t

[]