In [4]:
for i in range(10,20):
=    print (i)

10
11
12
13
14
15
16
17
18
19


In [7]:
import numpy as np
a = np.array([[[1,2,3],[2,3,4]], [[6,7,8],[8,7,6]], [[1,5,8],[9,9,3]]])
print (a.shape)

(3, 2, 3)


In [13]:
np.reshape(a, (a.shape[0], -2)).shape

(3, 6)

In [42]:
a= np.array([[1,2,3], [3,4,5], [4,2,9]])
b = np.array([2,0,1])
print (a)

[[1 2 3]
 [3 4 5]
 [4 2 9]]


In [39]:
c = np.array([(a[(np.arange(len(a))), b])])


In [53]:
print (c)
print (max(a-c.T))

[[3 3 2]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [33]:
a[(np.arange(len(a))), b] = 0
print (a)

[[1 2 0]
 [0 4 5]
 [4 0 9]]


In [48]:
max(0,a[1,1])

4

In [74]:
def maxx(x):
    t = max(0,x)
    return t
    #print (t)

In [75]:
f = np.vectorize(maxx)

In [82]:
print (a)


[[1 2 3]
 [3 4 5]
 [4 2 9]]


array([[2, 0, 4],
       [3, 0, 5]])

In [84]:
a= np.array([[1,2,-3], [3,-4,-5], [4,2,9]])
f = np.vectorize(maxx)
f(a)

array([[1, 2, 0],
       [3, 0, 0],
       [4, 2, 9]])

In [85]:
np.sum(a)

9